{
  "metadata": {
    "name": "Lego Island",
    "version": "1.0.7",
    "author": "Mindscape",
    "icon": "@local:icon.png",
    "appGroup": "entertainment"
  },
  "position": {
    "centered": true,
    "x": 0,
    "y": 0
  },
  "size": {
    "w": 1920,
    "h": 1080
  },
  "minSize": {
    "w": 640,
    "h": 480
  },
  "maxSize": {
    "w": 1920,
    "h": 1080
  },
  "state": {
    "minimized": false,
    "maximized": true,
    "headless": false,
    "resizable": false,
    "fullscreen": false,
    "overlay": true
  },
  "controls": {
    "minimize": true,
    "maximize": true,
    "close": true
  },
  "glass": true,
  "hidden": false,
  "core": false,
  "entrypoint": "isle.js",
  "id": "NikN_Lego_Island"
}